# vim: ft=zsh
# shellcheck disable=SC2030,SC2031,SC2034
# https://github.com/remino/dotfiles

# ########  ######  ##     ## ########   ######
#      ##  ##    ## ##     ## ##     ## ##    ##
#     ##   ##       ##     ## ##     ## ##
#    ##     ######  ######### ########  ##
#   ##           ## ##     ## ##   ##   ##
#  ##      ##    ## ##     ## ##    ##  ##    ##
# ########  ######  ##     ## ##     ##  ######
# .zshrc: Used for any interactive shells (including login).

################################################################################

# ######## ##     ## ####  ######  ########  ######
# ##        ##   ##   ##  ##    ##    ##    ##    ##
# ##         ## ##    ##  ##          ##    ##
# ######      ###     ##   ######     ##     ######
# ##         ## ##    ##        ##    ##          ##
# ##        ##   ##   ##  ##    ##    ##    ##    ##
# ######## ##     ## ####  ######     ##     ######

_plugin_exists() {
	# Can't use $ZSH_CUSTOM here as we check path before sourcing oh-my-zsh
	[ -d "$ZSH/plugins/$1" ] || [ -d "$ZSH/custom/plugins/$1" ]
}

_add_plugin() {
	plugins+=("$1")
}

_add_plugin_if_exists() {
	_plugin_exists "$1" || return
	_add_plugin "$1"
}

_unalias() {
	alias "$1" > /dev/null 2>&1 && unalias "$1"
}

_which_exists() {
	for cmd in "$@"
	do
		! ( _exists "$cmd" ) && continue
		echo "$cmd"
		return
	done
}

_is_demo() {
	[ -z "$DEMO" ] || [ "$DEMO" = "0" ]
}

# ########  ######## ########  ##     ##  ######
# ##     ## ##       ##     ## ##     ## ##    ##
# ##     ## ##       ##     ## ##     ## ##
# ##     ## ######   ########  ##     ## ##   ####
# ##     ## ##       ##     ## ##     ## ##    ##
# ##     ## ##       ##     ## ##     ## ##    ##
# ########  ######## ########   #######   ######

if [ -n "$ZSH_STARTUP_DEBUG" ] && [ "$ZSH_STARTUP_DEBUG" != "0" ]
then
	zmodload zsh/datetime > /dev/null 2>&1
	zmodload zsh/zprof > /dev/null 2>&1
	typeset -gF _zsh_startup_t0="$EPOCHREALTIME"
fi

#  ######   #######  ##     ## ########
# ##    ## ##     ## ###   ### ##     ##
# ##       ##     ## #### #### ##     ##
# ##       ##     ## ## ### ## ########
# ##       ##     ## ##     ## ##
# ##    ## ##     ## ##     ## ##
#  ######   #######  ##     ## ##

export ZSH_DISABLE_COMPFIX=true
export ZSH_COMPDUMP="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/.zcompdump-${ZSH_VERSION}"
mkdir -p "${XDG_CACHE_HOME:-$HOME/.cache}/zsh" > /dev/null 2>&1

# ######## ######## ########  ##     ##
#    ##    ##       ##     ## ###   ###
#    ##    ##       ##     ## #### ####
#    ##    ######   ########  ## ### ##
#    ##    ##       ##   ##   ##     ##
#    ##    ##       ##    ##  ##     ##
#    ##    ######## ##     ## ##     ##

if [[ -n $SSH_TTY && -z $COLORTERM ]]; then
	case $TERM in
		xterm-ghostty|xterm-kitty|xterm-256color|screen-256color|tmux-256color|wezterm|*-direct|*-truecolor)
			export COLORTERM=truecolor
			;;
	esac
fi

# ##     ##  #######  ##     ## ######## ########  ########  ######## ##      ##
# ##     ## ##     ## ###   ### ##       ##     ## ##     ## ##       ##  ##  ##
# ##     ## ##     ## #### #### ##       ##     ## ##     ## ##       ##  ##  ##
# ######### ##     ## ## ### ## ######   ########  ########  ######   ##  ##  ##
# ##     ## ##     ## ##     ## ##       ##     ## ##   ##   ##       ##  ##  ##
# ##     ## ##     ## ##     ## ##       ##     ## ##    ##  ##       ##  ##  ##
# ##     ##  #######  ##     ## ######## ########  ##     ## ########  ###  ###

# For M1 Macs, init Homebrew first:
if [ -x "/opt/homebrew/bin/brew" ]
then
	brew_shellenv_cache_dir="$XDG_CACHE_HOME/zsh"
	brew_shellenv_cache="$brew_shellenv_cache_dir/brew-shellenv.zsh"

	if [ ! -f "$brew_shellenv_cache" ] || [ "/opt/homebrew/bin/brew" -nt "$brew_shellenv_cache" ]
	then
		if mkdir -p "$brew_shellenv_cache_dir" > /dev/null 2>&1 && [ -w "$brew_shellenv_cache_dir" ]
		then
			/opt/homebrew/bin/brew shellenv > "$brew_shellenv_cache" 2> /dev/null
		fi
	fi

	if [ -s "$brew_shellenv_cache" ]
	then
		# shellcheck source=/dev/null
		source "$brew_shellenv_cache"
	else
		eval "$( /opt/homebrew/bin/brew shellenv )"
	fi

	unset brew_shellenv_cache_dir brew_shellenv_cache
fi

# Oh My Zsh plugin added later, after bundler plugin.

# ########     ##     #####   ##    ##
# ##     ##  ####    ##   ##  ##   ##
# ##     ##    ##   ##     ## ##  ##
# ########     ##   ##     ## #####
# ##           ##   ##     ## ##  ##
# ##           ##    ##   ##  ##   ##
# ##         ######   #####   ##    ##

if _is_demo
then
	ZSH_THEME="powerlevel10k/powerlevel10k"
else
	PS1="❯ "
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
# shellcheck source=/dev/null
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# ########     ###    ######## ##     ##
# ##     ##   ## ##      ##    ##     ##
# ##     ##  ##   ##     ##    ##     ##
# ########  ##     ##    ##    #########
# ##        #########    ##    ##     ##
# ##        ##     ##    ##    ##     ##
# ##        ##     ##    ##    ##     ##

if [ -z "$ZSH" ]
then
	for ZSH in "$HOME/.oh-my-zsh" "/opt/oh-my-zsh"
	do
		[ ! -d "$ZSH" ] && continue
		export ZSH
		[ ! -f "$ZSH/oh-my-zsh.sh" ] && unset ZSH && continue
		break
	done
fi

#  ######   ######  ##     ##            ###     ######   ######## ##    ## ########
# ##    ## ##    ## ##     ##           ## ##   ##    ##  ##       ###   ##    ##
# ##       ##       ##     ##          ##   ##  ##        ##       ####  ##    ##
#  ######   ######  ######### ####### ##     ## ##   #### ######   ## ## ##    ##
#       ##       ## ##     ##         ######### ##    ##  ##       ##  ####    ##
# ##    ## ##    ## ##     ##         ##     ## ##    ##  ##       ##   ###    ##
#  ######   ######  ##     ##         ##     ##  ######   ######## ##    ##    ##

share_ssh_agent() {
	[ -z "$SSH_AUTH_SOCK" ] && return
	# Remove old .ssh/agent file
	[ -f "$HOME/.ssh/agent" ] && rm -f "$HOME/.ssh/agent"
	ssh_agent_path="$HOME/.ssh/ssh-agent"
	printenv | grep '^SSH' | sed -E 's/^([^=]+)=(.*)$/\1="\2"; export \1;/' > "$ssh_agent_path"
}

share_ssh_agent

zstyle :omz:plugins:ssh-agent agent-forwarding yes
zstyle :omz:plugins:ssh-agent quiet yes

_add_plugin_if_exists ssh-agent

#    ###    ##       ####    ###     ######  ########  ######
#   ## ##   ##        ##    ## ##   ##    ## ##       ##    ##
#  ##   ##  ##        ##   ##   ##  ##       ##       ##
# ##     ## ##        ##  ##     ##  ######  ######    ######
# ######### ##        ##  #########       ## ##             ##
# ##     ## ##        ##  ##     ## ##    ## ##       ##    ##
# ##     ## ######## #### ##     ##  ######  ########  ######

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

[ -z "$EXT_IP_URL" ] && EXT_IP_URL="https://icanhazip.com"

alias anchor='anchor=$PWD'
alias c='cat'
alias copa='clipcopy; clippaste'
alias d='edit'
alias e='echo'
alias edit='eval "$EDITOR"'
alias expal='omz plugin load globalias'
alias f='printf'
alias findreadme="find . -iname 'readme\.*' -maxdepth 1"
alias lns='ln -s'
alias imgo='image_optim'
alias j='jeksite'
alias js='jekyll'
alias m='mansite'
alias mb='mansite build'
alias mbd='mansite -b deploy'
alias mbdp='mansite -b deploy && git push origin'
alias mdp='mansite deploy && git push origin'
alias mm='middleman'
alias extip4='curl -4Ls "$EXT_IP_URL" | xargs echo'
alias extip6='curl -6Ls "$EXT_IP_URL" | xargs echo'
alias extip='extip4'
alias noexpal='bindkey " " self-insert'
alias pa='ps aux'
alias pbcp='copa'
alias pg='pgrep'
alias pk='pkill'
alias pp='ps -auxwwf'
alias ppt='pstree -pn'
alias readme='cat $( findreadme )'
alias reload='. "$HOME/.zshrc"'
alias s='ssh'
alias showanchor='echo $anchor'
alias ssu='ssuu -'
alias ssuu='sudo su'
alias unanchor='unset anchor'
alias v=vi
alias zshrcedit='edit "$HOME/.zsh"{rc,env} "$XDG_CONFIG_HOME/zsh/"*/zsh*'
alias -g A='| xargs'
alias -g C='| command cat'
alias -g CC='| clipcopy'
alias -g CP='| clipcopy && clippaste'
alias -g CL='| wc -l'
alias -g J='| jq'
alias -g S='| sort'
alias -g U='| uniq'
alias -g X='| xargs'

if _exists code
then
	alias codea='code -a'
	alias codew='code -w'
fi

if _exists git
then
	alias gci='git commit -m "Initial commit"'
fi

if _exists msgcat
then
	alias colortest='msgcat --color=test'
fi

if _exists ssh
then
	alias sshp="ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no"
fi

if _exists tree
then
	alias tt=tree
	alias tree='tree -CNhp'
fi

if _exists vim
then
	alias vi=vim
	alias vim='vim -p'
fi

if _exists nvim
then
	# Override vi & vim alias
	alias vi=nvim
	alias vim=nvim
	alias neovim=nvim
fi

if ls --group-directories-first / > /dev/null 2>&1
then
	alias ls='ls --color=tty --group-directories-first'
fi

if _plugin_exists alias-finder
then
	_add_plugin alias-finder

	alias af='alias-finder'

	af_set() {
		zstyle ':omz:plugins:alias-finder' autoload "$1"
    zstyle ':omz:plugins:alias-finder' longer "$1"
    zstyle ':omz:plugins:alias-finder' exact "$1"
    zstyle ':omz:plugins:alias-finder' cheaper "$1"
	}

	af_disable() {
		af_set no
	}

	af_enable() {
		af_set yes
	}
fi

touchp() {
	[ -z "$1" ] && echo "Usage: touchp <file>" >&2 && return 1
	mkdir -p "$(dirname "$1")" && touch "$1"
}

# ########  #######  ##     ## #### ########  ########
#      ##  ##     ##  ##   ##   ##  ##     ## ##
#     ##   ##     ##   ## ##    ##  ##     ## ##
#    ##    ##     ##    ###     ##  ##     ## ######
#   ##     ##     ##   ## ##    ##  ##     ## ##
#  ##      ##     ##  ##   ##   ##  ##     ## ##
# ########  #######  ##     ## #### ########  ########
# Directories in cdpath are added to zoxide later.

if _exists zoxide; then
	[ -z "$ZSH_ZOXIDE_PRELOAD" ] && ZSH_ZOXIDE_PRELOAD=0

	alias cd=z
	alias cdi=zi

	_add_plugin_if_exists zoxide
fi

# ##    ##    ###    ######## ####
#  ##  ##    ## ##        ##   ##
#   ####    ##   ##      ##    ##
#    ##    ##     ##    ##     ##
#    ##    #########   ##      ##
#    ##    ##     ##  ##       ##
#    ##    ##     ## ######## ####

if _exists yazi; then
	function yy() {
		local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
		command yazi "$@" --cwd-file="$tmp"
		IFS= read -r -d '' cwd < "$tmp"
		[ "$cwd" != "$PWD" ] && [ -d "$cwd" ] && builtin cd -- "$cwd"
		command rm -f -- "$tmp"
	}
fi

# ########  ##       ##     ##  ######   #### ##    ##  ######
# ##     ## ##       ##     ## ##    ##   ##  ###   ## ##    ##
# ##     ## ##       ##     ## ##         ##  ####  ## ##
# ########  ##       ##     ## ##   ####  ##  ## ## ##  ######
# ##        ##       ##     ## ##    ##   ##  ##  ####       ##
# ##        ##       ##     ## ##    ##   ##  ##   ### ##    ##
# ##        ########  #######   ######   #### ##    ##  ######

for plugin in \
	aliases \
	catimg \
	command-not-found \
	common-aliases \
	copyfile \
	copypath \
	dirhistory \
	dirpersist \
	fancy-ctrl-z \
	jump \
	macos \
	urltools \
	vi-mode
do
	_add_plugin_if_exists "$plugin"
done

cat <<LIST | while read -r cmd add
aws
base64 encode64
bundle bundler
chroma colorize
code vscode
date isodate
deno
fd
fd fdfind
gcloud
gh
git git git-aliases
git-extras
git-lfs
gpg-agent
imgmod
mkprj cdmp
mycli mycli-alias
mysql mysql-alias
node
op 1password
pip
rg
rsync cp rsync
ruby
sesh
sudo
system
thefuck
ufw
vidmod
wp wp-cli
yt-dlp

brew
yadm yadm-aliases
LIST
do
	[ -z "$cmd" ] && continue
	[ -z "$add" ] && add="$cmd"
	_exists "$cmd" || continue

	echo "$add" | tr ' ' '\n' | while read -r plugin
	do
		_add_plugin_if_exists "$plugin"
	done
done

# ##     ## ####  ######  ########
# ###   ###  ##  ##    ## ##
# #### ####  ##  ##       ##
# ## ### ##  ##   ######  ######
# ##     ##  ##        ## ##
# ##     ##  ##  ##    ## ##
# ##     ## ####  ######  ########

# Use mise shims instead of its dynamic shell hook. This keeps mise-managed
# tool selection while avoiding generated eval/unset code during shell startup.
if _exists mise
then
	# shellcheck source=/dev/null
	source <(command mise activate zsh --shims)
fi

# ######## ######## ########
# ##            ##  ##
# ##           ##   ##
# ######      ##    ######
# ##         ##     ##
# ##        ##      ##
# ##       ######## ##

if _exists fzf; then
	# Let fzf provide its own integration instead of using Oh My Zsh's legacy
	# fzf plugin. The latter guesses installation directories and mistakes the
	# pkgsrc prefix (/usr/pkg on NetBSD) for fzf's source directory.
	if fzf --zsh > /dev/null 2>&1
	then
		# shellcheck source=/dev/null
		source <(fzf --zsh)
	fi

	if _plugin_exists fzf-tab
	then
		_add_plugin fzf-tab
	fi
fi

# fzf-tab must load after completion providers, but before ZLE wrappers such
# as zsh-syntax-highlighting.
_add_plugin_if_exists zsh-syntax-highlighting

# ########     ###    ########
# ##     ##   ## ##      ##
# ##     ##  ##   ##     ##
# ########  ##     ##    ##
# ##     ## #########    ##
# ##     ## ##     ##    ##
# ########  ##     ##    ##

BATCMD="$( _which_exists batcat bat )"

if [ -n "$BATCMD" ]
then
	alias bat="\$BATCMD --tabs=2 --style=full --pager 'less -RX'"
	alias cat=less
	alias less="bat -p"
	alias -g B='| $BATCMD'
	alias -g BL='| $BATCMD -pp -l log'
	alias -g BJ='| $BATCMD -pp -l json'

	if [ "$BATCMD" != "batcat" ]
	then
		alias batcat=bat
	fi
fi

baturl() {
	[ -z "$BATCMD" ] && echo "bat required" >&2 && return 1
	[ $# -lt 1 ] && echo "Usage: burl <url> [<bat_args>]" && return
	url="$1"
	shift
	curl -Ls -D - "$url" | bat "$@"
}

# ########         ######## #### ########
# ##    ##              ##   ##  ##     ##
#     ##               ##    ##  ##     ##
#    ##    #######    ##     ##  ########
#   ##               ##      ##  ##
#   ##              ##       ##  ##
#   ##             ######## #### ##

if _exists 7zz; then
	if ! alias 7z >/dev/null 2>&1; then
		alias 7z=7zz
	fi
fi

# ######## ########  #### ########  #######  ########
# ##       ##     ##  ##     ##    ##     ## ##     ##
# ##       ##     ##  ##     ##    ##     ## ##     ##
# ######   ##     ##  ##     ##    ##     ## ########
# ##       ##     ##  ##     ##    ##     ## ##   ##
# ##       ##     ##  ##     ##    ##     ## ##    ##
# ######## ########  ####    ##     #######  ##     ##

editor() {
	[ $# -gt 0 ] && export EDITOR="$1"
	echo "$EDITOR"
}

# Preferred editor for local and remote sessions
if _exists nvim
then
	editor nvim > /dev/null
else
	editor vim > /dev/null
fi

# ##    ## ########  ##     ##
# ###   ## ##     ## ###   ###
# ####  ## ##     ## #### ####
# ## ## ## ########  ## ### ##
# ##  #### ##        ##     ##
# ##   ### ##        ##     ##
# ##    ## ##        ##     ##

if _exists npm
then
	alias npma='npm add'
	alias npmb='npm run build'
	alias npmd='npm run dev'
	alias npmdo='npm run docs'
	alias npmi='npm install'
	alias npml='npm ls'
	alias npmr='npm run'

	_add_plugin_if_exists npm
fi

# ########   #######   #######  ########
# ##     ## ##     ## ##     ##    ##
# ##     ## ##     ## ##     ##    ##
# ########  ##     ## ##     ##    ##
# ##   ##   ##     ## ##     ##    ##
# ##    ##  ##     ## ##     ##    ##
# ##     ##  #######   #######     ##

if [ "$USER" = "root" ]
then
	cdpath+=(
		"/etc"
		"/opt"
		"/opt/$HOST"
		"/var/log"
		"/var/www"
	)
fi

# ######## ##     ## ##     ## ##     ##
#    ##    ###   ### ##     ##  ##   ##
#    ##    #### #### ##     ##   ## ##
#    ##    ## ### ## ##     ##    ###
#    ##    ##     ## ##     ##   ## ##
#    ##    ##     ## ##     ##  ##   ##
#    ##    ##     ##  #######  ##     ##

ZSH_TMUX_AUTOQUIT=false
ZSH_TMUX_AUTONAME_SESSION=false
ZSH_TMUX_AUTOREFRESH=true
ZSH_TMUX_CONFIG="$XDG_CONFIG_HOME/tmux/tmux.conf"
ZSH_TMUX_DEFAULT_SESSION_NAME=main
ZSH_TMUX_UNICODE=true

if [ "$USER" = "root" ]
then
	ZSH_TMUX_AUTOSTART=false
else
	ZSH_TMUX_AUTOSTART=true
fi

if _exists tmux
then
	alias tmuxlc='tmux source "$ZSH_TMUX_CONFIG"'
	alias tx=tmux
	_add_plugin_if_exists tmux
	_add_plugin_if_exists remino-tmux
fi

# ###### ##     ## ##   ## ##     ## ## ##    ##   ###   ######  #####  ######
#   ##   ###   ### ##   ##  ##   ##  ## ###   ##  ## ##    ##   ##   ## ##   ##
#   ##   #### #### ##   ##   ## ##   ## ####  ## ##   ##   ##   ##   ## ##   ##
#   ##   ## ### ## ##   ##    ###    ## ## ## ## ##   ##   ##   ##   ## ######
#   ##   ##     ## ##   ##   ## ##   ## ##  #### #######   ##   ##   ## ## ##
#   ##   ##     ## ##   ##  ##   ##  ## ##   ### ##   ##   ##   ##   ## ##  ##
#   ##   ##     ##  #####  ##     ## ## ##    ## ##   ##   ##    #####  ##   ##

if _exists tmuxinator
then
	_add_plugin tmuxinator

	alias txS='tmuxinator stop'
fi

# ######## ########     ###     ######  ##     ##
#    ##    ##     ##   ## ##   ##    ## ##     ##
#    ##    ##     ##  ##   ##  ##       ##     ##
#    ##    ########  ##     ##  ######  #########
#    ##    ##   ##   #########       ## ##     ##
#    ##    ##    ##  ##     ## ##    ## ##     ##
#    ##    ##     ## ##     ##  ######  ##     ##

if _exists trash
then
	alias rm='trash -F'
fi

# ##    ##    ###    ########  ##     ##
#  ##  ##    ## ##   ##     ## ###   ###
#   ####    ##   ##  ##     ## #### ####
#    ##    ##     ## ##     ## ## ### ##
#    ##    ######### ##     ## ##     ##
#    ##    ##     ## ##     ## ##     ##
#    ##    ##     ## ########  ##     ##

if _exists yadm
then
	cat <<ALIASES | while read -r alias cmd

a
ap
c
co
lo
pl
po
st
ALIASES
	do
		[ -z "$cmd" ] && cmd="$alias"
		# shellcheck disable=SC2139
		alias "y$alias"="yadm $cmd"
	done
fi

# ########  ##    ## ########  ##     ##
# ##     ## ###   ## ##     ## ###   ###
# ##     ## ####  ## ##     ## #### ####
# ########  ## ## ## ########  ## ### ##
# ##        ##  #### ##        ##     ##
# ##        ##   ### ##        ##     ##
# ##        ##    ## ##        ##     ##

[ -z "$PNPM_HOME" ] && PNPM_HOME="$HOME/Library/pnpm"

if [ -d "$PNPM_HOME" ]
then
	export PNPM_HOME
	export PATH="$PNPM_HOME:$PATH"
	_add_plugin_if_exists pnpm
fi

# ########  ########  ######## ######## ######## #### ######## ########
# ##     ## ##     ## ##          ##       ##     ##  ##       ##     ##
# ##     ## ##     ## ##          ##       ##     ##  ##       ##     ##
# ########  ########  ######      ##       ##     ##  ######   ########
# ##        ##   ##   ##          ##       ##     ##  ##       ##   ##
# ##        ##    ##  ##          ##       ##     ##  ##       ##    ##
# ##        ##     ## ########    ##       ##    #### ######## ##     ##

if _exists prettier
then
	alias prettycss='prettier --stdin-filepath style.css'
	alias prettyhtml='prettier --stdin-filepath index.html'
	alias prettyjs='prettier --stdin-filepath script.js'
fi

# ######## ##     ## ##    ##  ######  ######## ####  #######  ##    ##  ######
# ##       ##     ## ###   ## ##    ##    ##     ##  ##     ## ###   ## ##    ##
# ##       ##     ## ####  ## ##          ##     ##  ##     ## ####  ## ##
# ######   ##     ## ## ## ## ##          ##     ##  ##     ## ## ## ##  ######
# ##       ##     ## ##  #### ##          ##     ##  ##     ## ##  ####       ##
# ##       ##     ## ##   ### ##    ##    ##     ##  ##     ## ##   ### ##    ##
# ##        #######  ##    ##  ######     ##    ####  #######  ##    ##  ######

fancyhostname() {
	hostname \
		| ( ( _exists figlet && figlet -f standard ) || command cat ) \
		| ( ( _exists lolcat && lolcat ) || command cat ) \
		;
}

mdcd() {
	[ $# -lt 1 ] && "Usage: mdcd <dir>"
	mkdir -p "$1"
	cd "$1"
}

minifetch() {
	fancyhostname
	printf "%s@%s %s %s\n" "$USER" "$( hostname )" "$( extip )"
	uptime
	echo
	_exists fortune && fortune -s
}

compactfetch() {
	_exists fastfetch || return
	fastfetch --config "${XDG_CONFIG_HOME:-$HOME/.config}/fastfetch/compact.jsonc"
}

unifetch() {
	for msgsrc in fastfetch neofetch pfetch minifetch
	do
		_exists "$msgsrc" && break
	done

	if [ "$msgsrc" != "minifetch" ]
	then
		"$msgsrc"
	else
		minifetch
	fi
}

alias sysinfo=unifetch

_unalias k
k() {
	if [ -f bun.lockb ]; then
		command bun "$@"
	elif [ -f yarn.lock ]; then
		command yarn "$@"
	elif [ -f package-lock.json ]; then
		command npm "$@"
	else
		command pnpm "$@"
	fi
}

# Show control characters
# (Does not work with Powerlevel10k.)
TRAPINT() {
  print -n "^C"
  return $(( 128 + $1 ))
}

# ##        #######   ######     ###    ##
# ##       ##     ## ##    ##   ## ##   ##
# ##       ##     ## ##        ##   ##  ##
# ##       ##     ## ##       ##     ## ##
# ##       ##     ## ##       ######### ##
# ##       ##     ## ##    ## ##     ## ##
# ########  #######   ######  ##     ## ########

for include in "$HOME/.zshrc.local" "$XDG_CONFIG_HOME/zsh/local" "$XDG_CONFIG_HOME/zsh/local/zshrc"
do
	[ ! -f "$include" ] && continue
	# shellcheck source=/dev/null
	source "$include"
done

#  ######    #######
# ##    ##  ##     ##
# ##        ##     ##
# ##   #### ##     ##
# ##    ##  ##     ##
# ##    ##  ##     ##
#  ######    #######

if _exists go
then
	_add_plugin_if_exists golang

	[ -z "$GOPATH" ] && export GOPATH="$XDG_DATA_HOME/go"
	[ -z "$GOROOT" ] && export GOROOT="$( go env GOROOT )"

	path+=("$GOPATH/bin" "$GOROOT/bin")

	export path
fi

#  #######   ######   ######  ########  #######
# ##     ## ##    ## ##    ## ##       ##     ##
# ##     ## ##       ##       ##              ##
# ##     ##  ######  ##       #######   #######
# ##     ##       ## ##             ## ##
# ##     ## ##    ## ##    ## ##    ## ##
#  #######   ######   ######   ######  #########

if _exists osc52
then
	alias -g O='| osc52copy'
	alias 52c=osc52copy
	alias 52p=osc52paste
fi

# ##     ## ########  ######   ######     ###     ######   ########
# ###   ### ##       ##    ## ##    ##   ## ##   ##    ##  ##
# #### #### ##       ##       ##        ##   ##  ##        ##
# ## ### ## ######    ######   ######  ##     ## ##   #### ######
# ##     ## ##             ##       ## ######### ##    ##  ##
# ##     ## ##       ##    ## ##    ## ##     ## ##    ##  ##
# ##     ## ########  ######   ######  ##     ##  ######   ########

MESSAGE_FONT=( termino )

_message_figlet() {
	local termino_dir font font_dir
	local -a font_dirs

	font_dirs=(
		"$HOME/.local/share/figlet"
		/usr/local/share/figlet
	)

	for font in "${MESSAGE_FONT[@]}"
	do
		if figlet -f "$font" " " > /dev/null 2>&1
		then
			figlet -f "$font"
			return
		fi

		for font_dir in "${font_dirs[@]}"
		do
			if [ -f "$font_dir/$font.flf" ]
			then
				figlet -d "$font_dir" -f "$font"
				return
			fi
		done

		if [ "$font" = termino ] && _exists brew
		then
			termino_dir="$( brew --prefix termino 2> /dev/null )/share/figlet"
			if printf "font-probe\\n" | figlet -d "$termino_dir" -f "$font" > /dev/null 2>&1
			then
				figlet -d "$termino_dir" -f "$font"
				return
			fi
		fi
	done

	figlet -f banner
}

idbanner() {
	_exists figlet || return

	local user="$( whoami )"
	local host="@$( hostname )"
	local ident="$user$host"

	if _exists lolcat
	then
		local seed="${IDBANNER_SEED:-$( printf "%d" "$( printf "0x%s" "$( printf "%s" "$ident" | md5sum | cut -c1-4 )" )" | awk '{print $1 % 10000}' )}"
		printf "%s\\n%s\\n" "$user" "$host" | _message_figlet | lolcat -S "$seed"
		return
	fi

	printf "%s\\n%s\\n" "$user" "$host" | _message_figlet
}

intro() {
	if type _private_msg > /dev/null 2>&1
	then
		_private_msg && echo
	else
		idbanner && echo
	fi

	compactfetch && echo

	if _exists fortune
	then
		fortune -e -s && echo
	fi
}

if _is_demo
then
	repeat $(( LINES / 2 )) echo
	intro
fi

#  ######  ##    ##    ###    ########
# ##    ## ###   ##   ## ##   ##     ##
# ##       ####  ##  ##   ##  ##     ##
#  ######  ## ## ## ##     ## ########
#       ## ##  #### ######### ##
# ##    ## ##   ### ##     ## ##
#  ######  ##    ## ##     ## ##

_exists snap && _add_plugin_if_exists snap

#  #######  ##     ##         ##     ## ##    ##         ########  ######  ##     ##
# ##     ## ##     ##         ###   ###  ##  ##               ##  ##    ## ##     ##
# ##     ## ##     ##         #### ####   ####               ##   ##       ##     ##
# ##     ## ######### ####### ## ### ##    ##    #######    ##     ######  #########
# ##     ## ##     ##         ##     ##    ##              ##           ## ##     ##
# ##     ## ##     ##         ##     ##    ##             ##      ##    ## ##     ##
#  #######  ##     ##         ##     ##    ##            ########  ######  ##     ##

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Load Oh My Zsh's strict matcher first. It is replaced after Oh My Zsh loads
# with an exact-case-first fallback matcher (see below).
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Use a custom terminal title hook below instead of Oh My Zsh's default one.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# The waiting-dots wrapper forces a ZLE redraw that shifts the multiline
# Powerlevel10k prompt after a completion attempt with no matches.
COMPLETION_WAITING_DOTS="false"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Path to your oh-my-zsh installation.
[ -n "$ZSH" ] && source "$ZSH/oh-my-zsh.sh"

# Outside tmux, reflect the prompt directory or the command currently running
# in the terminal title. tmux owns the outer title for its own clients.
if [[ -z "$TMUX" ]]; then
	_terminal_title() {
		local title=$1
		title=${title//$'\e'/}
		title=${title//$'\a'/}
		title=${title//$'\n'/ }
		title=${title//$'\r'/ }
		print -rn -- $'\e]2;'"$title"$'\a'
	}

	_terminal_title_precmd() {
		_terminal_title "${HOST%%.*}:${PWD:t}"
	}

	_terminal_title_preexec() {
		_terminal_title "${HOST%%.*}:$1"
	}

	autoload -Uz add-zsh-hook
	add-zsh-hook precmd _terminal_title_precmd
	add-zsh-hook preexec _terminal_title_preexec
fi

#  #######  ########  ######## ####  #######  ##    ##  ######
# ##     ## ##     ##    ##     ##  ##     ## ###   ## ##    ##
# ##     ## ##     ##    ##     ##  ##     ## ####  ## ##
# ##     ## ########     ##     ##  ##     ## ## ## ##  ######
# ##     ## ##           ##     ##  ##     ## ##  ####       ##
# ##     ## ##           ##     ##  ##     ## ##   ### ##    ##
#  #######  ##           ##    ####  #######  ##    ##  ######

setopt AUTO_LIST
setopt CHECK_JOBS
setopt CORRECT
setopt PATH_DIRS

# Prefer exact-case candidates, then fall back to case-insensitive and
# substring matching. This keeps `exa<Tab>` on lowercase `example` instead of
# inserting `Exa`, while still allowing `Ze<Tab>` and `Er<Tab>` to find `zero`.
zstyle ':completion:*' matcher-list \
	'' \
	'm:{[:lower:]-_}={[:upper:]_-}' \
	'm:{[:upper:]-_}={[:lower:]_-}' \
	'l:|=* r:|=*' \
	'm:{[:lower:]-_}={[:upper:]_-} l:|=* r:|=*' \
	'm:{[:upper:]-_}={[:lower:]_-} l:|=* r:|=*'

# Complete at an empty prompt instead of inserting a literal tab character.
zstyle ':completion:*' insert-tab no

# fzf-tab renders the selection UI itself. Keep zsh's menu available when the
# plugin is absent and normal completion is the fallback.
if (( ${plugins[(Ie)fzf-tab]} ))
then
	zstyle ':completion:*' menu no
fi

# ######## ########    ###
# ##            ##    ## ##
# ##           ##    ##   ##
# ######      ##    ##     ##
# ##         ##     #########
# ##        ##      ##     ##
# ######## ######## ##     ##

if _exists eza
then
	alias eza='eza --color-scale --classify --git --group-directories-first --icons --time-style=long-iso'
	alias l='eza -la'
	alias lg='eza -laG'
	alias ls=eza
	alias ll='eza -l'
	alias la='ll -AF'
	alias tree='ll -T'
	alias exa='eza'
elif _exists exa
then
	alias exa='exa --color-scale --classify --git --group-directories-first --icons --time-style=long-iso'
	alias l='exa -la'
	alias lg='exa -laG'
	alias ls=exa
	alias ll='exa -l'
	alias la='ll -AF'
	alias tree='ll -T'
fi

#    ###    ######## ##     ## #### ##    ##
#   ## ##      ##    ##     ##  ##  ###   ##
#  ##   ##     ##    ##     ##  ##  ####  ##
# ##     ##    ##    ##     ##  ##  ## ## ##
# #########    ##    ##     ##  ##  ##  ####
# ##     ##    ##    ##     ##  ##  ##   ###
# ##     ##    ##     #######  #### ##    ##

_exists atuin && eval "$(atuin init zsh)"

# ##     ##  ######
# ###   ### ##    ##
# #### #### ##
# ## ### ## ##
# ##     ## ##
# ##     ## ##    ##
# ##     ##  ######

[ -f "${XDG_DATA_HOME:-"$HOME/.local/share"}/mc/skins/cyberwave.ini" ] && export MC_SKIN=cyberwave

if _exists mc
then
	alias mc='mc --nosubshell'
fi

# ######## ########
# ##       ##     ##
# ##       ##     ##
# ######   ##     ##
# ##       ##     ##
# ##       ##     ##
# ##       ########

if _exists fdfind && ! type -p fd > /dev/null 2>&1
then
	if alias fd > /dev/null 2>&1 && ! _exists fD
	then
		_old_cmd="$( alias fd | sed -E "s/^[^=]*=[[:space:]]*//;s/[[:space:]]*$//;s/^'//;s/'$//" )"
		alias fD="$_old_cmd"
		unset _old_cmd
	fi

	alias fd=fdfind
fi

# ##    ## ########         ########  ##       ########
#  ##  ##     ##            ##     ## ##       ##     ##
#   ####      ##            ##     ## ##       ##     ##
#    ##       ##    ####### ##     ## ##       ########
#    ##       ##            ##     ## ##       ##
#    ##       ##            ##     ## ##       ##
#    ##       ##            ########  ######## ##

if _exists yt-dlp
then
	alias youtube-dl='yt-dlp'
	alias ydl='yt-dlp'
fi

#  ######  ########
# ##    ## ##     ##
# ##       ##     ##
# ##       ##     ##
# ##       ##     ##
# ##    ## ##     ##
#  ######  ########

cdpath+=("$HOME")

if (( $+commands[zoxide] )) ; then
	add_cdpath_to_zoxide() {
		local pths=()

		setopt null_glob

		for pth in $cdpath; do
			[[ ! -d "$pth" ]] && continue
			for dir in $pth/*(-/N); do
				zoxide add "$dir"
			done
		done

		unsetopt null_glob
	}

	[ "$ZSH_ZOXIDE_PRELOAD" = "1" ] && add_cdpath_to_zoxide
fi

#  ######  ##       ########    ###    ##    ## ##     ## ########
# ##    ## ##       ##         ## ##   ###   ## ##     ## ##     ##
# ##       ##       ##        ##   ##  ####  ## ##     ## ##     ##
# ##       ##       ######   ##     ## ## ## ## ##     ## ########
# ##       ##       ##       ######### ##  #### ##     ## ##
# ##    ## ##       ##       ##     ## ##   ### ##     ## ##
#  ######  ######## ######## ##     ## ##    ##  #######  ##

unset -f \
	_add_plugin \
	_add_plugin_if_exists \
	_which_exists \
	_is_demo \
	_plugin_exists \
	_unalias \
	;

# ########   #######   ######  ########
# ##     ## ##     ## ##    ##    ##
# ##     ## ##     ## ##          ##
# ########  ##     ##  ######     ##
# ##        ##     ##       ##    ##
# ##        ##     ## ##    ##    ##
# ##         #######   ######     ##

if declare -f _post_init > /dev/null 2>&1
then
	_post_init
	unset -f _post_init
fi

if [ -n "$_zsh_startup_t0" ]
then
	typeset -F3 _zsh_startup_elapsed
	_zsh_startup_elapsed="$(( EPOCHREALTIME - _zsh_startup_t0 ))"
	printf '[zsh-startup] %.3fs\n' "$_zsh_startup_elapsed"
	type zprof > /dev/null 2>&1 && zprof
	unset _zsh_startup_elapsed _zsh_startup_t0
fi
