#!/usr/bin/env bash

bootstrap_main() {
	system_type=$(uname -s)

	_run_if_exists "$( dirname "${BASH_SOURCE[0]}" )/install_zshrc"

	if [ ! -d "$HOME/.config/nvim" ]; then
		git clone git@github.com:remino/nvim.git "$HOME/.config/nvim"
	fi

	[ ! -d "$HOME/.gnupg" ] && mkdir -p "$HOME/.gnupg"
	[ ! -f "$HOME/.gnupg/gpg.local.conf" ] && touch "$HOME/.gnupg/gpg.local.conf"

	case "$system_type" in
		Darwin|Linux) ;;
		*) touch "$HOME/.gnupg/gpg-agent.$system_type.conf" ;;
	esac

	local config_dir="${XDG_CONFIG_HOME:-$HOME/.config}"
	[ ! -d "$config_dir/yt-dlp" ] && mkdir -p "$config_dir/yt-dlp"
	[ ! -f "$config_dir/yt-dlp/config.local" ] && touch "$config_dir/yt-dlp/config.local"
}

_run_if_exists() {
	if [ -x "$1" ]; then
		"$@"
	fi
}

bootstrap_main
