#!/usr/bin/env bash

install_zshrc() {
	_add_line "$(_zshrc_line)" "$HOME/.zshrc"
}

_add_line() {
	if ! _has_line "$1" "$2"; then
		echo "$1" >> "$2"
	fi
}

_has_line() {
	grep -F -q "$1" "$2" 2> /dev/null
}

_zshrc_line() {
	cat << EOF
{ ZSHBASE="\${XDG_CONFIG_HOME:-\$HOME/.config}/zsh/base/zshrc"; [ -f "\$ZSHBASE" ] && source "\$ZSHBASE"; unset ZSHBASE; }
EOF
}

install_zshrc
