#!/usr/bin/env bash

install_zshrc() {
	for i in zshenv zshrc; do
		_add_line "$(_source_line $i)" "$HOME/.$i"
	done
}

_add_line() {
	if ! _has_line "$1" "$2"; then
		echo "$1" >> "$2"
	fi
}

_has_line() {
	grep -F -q "$1" "$2" 2> /dev/null
}

_source_line() {
	cat << EOF
{ ZSHBASE="\${XDG_CONFIG_HOME:-\$HOME/.config}/zsh/base/$1"; [ -f "\$ZSHBASE" ] && source "\$ZSHBASE"; unset ZSHBASE; }
EOF
}

install_zshrc
