FROM debian:bookworm-slim

RUN apt-get update \
	&& apt-get install -y --no-install-recommends ca-certificates curl git python3 yadm zsh \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /src
COPY . .
ARG INSTALLER_URL=
RUN zsh ./.config/dotfiles/tests/zsh_intro.zsh
RUN INSTALLER_URL="$INSTALLER_URL" ./.config/dotfiles/tests/portable.sh
