FROM debian:bookworm-slim

RUN apt-get update \
	&& apt-get install -y --no-install-recommends ca-certificates git yadm zsh \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /src
COPY . .
RUN ./.config/dotfiles/tests/yadm.sh
